language: julia
os:
  - linux
  - osx

julia:
  - 1.1
  - nightly
notifications:

services:
  - docker

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ --color=yes docs/make.jl pdf clean
      after_success: skip

after_success:
    - julia -e 'import Pkg; 
                cd(Pkg.dir("GeoEfficiency")); 
                Pkg.add("Coverage"); using Coverage; 
                const fileCoverage = process_folder(); 
                Coveralls.submit(fileCoverage);
                Codecov.submit(fileCoverage);'
