language: julia
os:
  - linux
  - osx
  

julia:
  - 1.1
  - nightly
notifications:

#codecov: true
#coveralls: true
after_success:
  - julia --project=coverage/ -e 'using Pkg; Pkg.instantiate()'
  - julia --project=coverage/ coverage/coverage.jl

services:
  - docker

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ --color=yes docs/make.jl pdf clean
      name: "HTML/PDF"
      after_success: skip
      services: docker

    - script:
      - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - julia --project=docs/ --color=yes docs/mkdocs.jl 
      name: "Markdown/MkDocs"
      after_success: skip
